version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/react-docker:delegated
      - /node_modules
      - /public
    ports:
      - "8080:8080"
    environment:
      - WATCHPACK_POLLING=true